In [3]:
# ==========================================================
# AI Banking Assistant
# Step 8 - Train Multiple Machine Learning Models
# ==========================================================


import warnings
warnings.filterwarnings("ignore")


import numpy as np
import pandas as pd
import joblib
import os


from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


from sklearn.svm import SVC


from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# XGBoost

xgb_available = True

try:
    from xgboost import XGBClassifier

except:

    xgb_available = False



# ==========================================================
# Load Processed Data
# ==========================================================


X_train = np.load(
    "../datasets/processed/X_train.npy"
)


X_test = np.load(
    "../datasets/processed/X_test.npy"
)


y_train = np.load(
    "../datasets/processed/y_train.npy"
)


y_test = np.load(
    "../datasets/processed/y_test.npy"
)



print("="*80)
print("PROCESSED DATA LOADED")
print("="*80)


print("\nTraining Data:", X_train.shape)

print("Testing Data :", X_test.shape)



# ==========================================================
# Define Models
# ==========================================================


models = {


"Logistic Regression":
    LogisticRegression(
        max_iter=1000
    ),


"Decision Tree":
    DecisionTreeClassifier(
        random_state=42
    ),


"Random Forest":
    RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ),


"Support Vector Machine":
    SVC(
        kernel="rbf"
    )

}



if xgb_available:


    models["XGBoost"] = XGBClassifier(

        random_state=42,

        eval_metric="logloss"

    )



# ==========================================================
# Training
# ==========================================================


results=[]


best_accuracy=0

best_model=None

best_model_name=""


print("\n")

print("="*80)

print("MODEL TRAINING STARTED")

print("="*80)



for name,model in models.items():


    print("\nTraining:",name)


    model.fit(

        X_train,

        y_train

    )


    prediction=model.predict(

        X_test

    )


    accuracy=accuracy_score(

        y_test,

        prediction

    )


    precision=precision_score(

        y_test,

        prediction

    )


    recall=recall_score(

        y_test,

        prediction

    )


    f1=f1_score(

        y_test,

        prediction

    )



    results.append([

        name,

        accuracy,

        precision,

        recall,

        f1

    ])



    print("Accuracy :",round(accuracy,4))

    print("Precision:",round(precision,4))

    print("Recall   :",round(recall,4))

    print("F1 Score :",round(f1,4))



    print("\nConfusion Matrix")

    print(
        confusion_matrix(
            y_test,
            prediction
        )
    )


    if accuracy > best_accuracy:


        best_accuracy=accuracy

        best_model=model

        best_model_name=name




# ==========================================================
# Model Comparison
# ==========================================================


results_df=pd.DataFrame(

    results,

    columns=[

        "Model",

        "Accuracy",

        "Precision",

        "Recall",

        "F1 Score"

    ]

)



results_df=results_df.sort_values(

    by="Accuracy",

    ascending=False

)



print("\n")

print("="*80)

print("MODEL COMPARISON")

print("="*80)


display(results_df)



# ==========================================================
# Save Best Model
# ==========================================================


os.makedirs(

    "../models",

    exist_ok=True

)



joblib.dump(

    best_model,

    "../models/loan_model.pkl"

)



print("\n")

print("="*80)

print("BEST MODEL SAVED")

print("="*80)



print("Best Model:",best_model_name)

print(
    "Accuracy:",
    round(best_accuracy,4)
)


print(
    "\nSaved Location:"
)

print(
    "../models/loan_model.pkl"
)

PROCESSED DATA LOADED

Training Data: (491, 14)
Testing Data : (123, 14)


MODEL TRAINING STARTED

Training: Logistic Regression
Accuracy : 0.8618
Precision: 0.84
Recall   : 0.9882
F1 Score : 0.9081

Confusion Matrix
[[22 16]
 [ 1 84]]

Training: Decision Tree
Accuracy : 0.7317
Precision: 0.825
Recall   : 0.7765
F1 Score : 0.8

Confusion Matrix
[[24 14]
 [19 66]]

Training: Random Forest
Accuracy : 0.8374
Precision: 0.8495
Recall   : 0.9294
F1 Score : 0.8876

Confusion Matrix
[[24 14]
 [ 6 79]]

Training: Support Vector Machine
Accuracy : 0.8537
Precision: 0.8317
Recall   : 0.9882
F1 Score : 0.9032

Confusion Matrix
[[21 17]
 [ 1 84]]


MODEL COMPARISON


,Model,Accuracy,Precision,Recall,F1 Score
0,Logistic Regression,0.861789,0.840000,0.988235,0.908108
3,Support Vector Machine,0.853659,0.831683,0.988235,0.903226
2,Random Forest,0.837398,0.849462,0.929412,0.887640
1,Decision Tree,0.731707,0.825000,0.776471,0.800000




BEST MODEL SAVED
Best Model: Logistic Regression
Accuracy: 0.8618

Saved Location:
../models/loan_model.pkl
